//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NASTC.Web.API.Resources
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ETT_NASTC_LocalEntities : DbContext
    {
        public ETT_NASTC_LocalEntities()
            : base("name=ETT_NASTC_LocalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Nastc_Application> Nastc_Application { get; set; }
        public DbSet<Nastc_Member_Details> Nastc_Member_Details { get; set; }
    }
}
