//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NASTC.Web.API.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nastc_Application
    {
        public long Application_Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public long Developer_Id { get; set; }
        public string App_Id { get; set; }
        public string Public_Key { get; set; }
        public string Private_Key { get; set; }
        public bool Is_Deleted { get; set; }
        public System.DateTime Created_Time_Stamp { get; set; }
        public System.DateTime Updated_Time_Stamp { get; set; }
    }
}
